### ISSUE TITLE
Movie Model

### ISSUE THREAD

**Issue by maggielove** [Kalfis/moviegoer_app#2]
Create movie model 

Include:
-title
-genre 
-plot summary/ teaser
-release date
-user comments (for upcoming or review)
-user rating?
-bonus: average rating of all users

**Comment by luisarce5** [comment]
Completed movie.js which contains the schema for 'mymovies'.
Committed and pushed movie.js to luis branch in GitHub.
I created a sample item in Mongo database locally in order to test it.
I used  $mongo in terminal to create locally a database named 'moviegoer', and a collection called 'mymovies'.  See comments to Issue #13 for further details on the commands used in Mongo. 
I named the collection 'mymovies' in order to differentiate the movies selected by a given user ('mymovies') from any other movies data that we might pull from the 3rd party API.

**Comment by maggielove** [comment]
Would comments be a String or an array of objects? Not sure how this would look exactly..

**Comment by luisarce5** [comment]
Yeah, an array of objects is more suitable.  Actually, more precisely, an array of strings.  I'll edit code accordingly for next round.

**Comment by maggielove** [comment]
I'm using the movie model to build out the seed.js file--I saw the last line of the schema is 
`comments: [String],`

1) I think we need to remove the comma since it's the last line
2) What do we want comments to be? What if to start, we have it as a String (only the user can comment, as a note/review to herself)--and eventually we can maybe give users the option to comment on each other's movies?

**Comment by luisarce5** [comment]
1) agreed, proper syntax. 

2) we could still leave it as an array of strings. So, to start it will only store one single comment as a string in an array of one item. Then, later we could just push additional comments as strings into the array if we let a user add multiple comments to a movie, or let other users comment, w/o having to change the type of variable.
